--Question 1
WITH 
E1 AS (SELECT CITES.CITEDBOOKNO FROM CITES NATURAL JOIN BOOK WHERE BOOK.PRICE < 50)
SELECT DISTINCT CITEDBOOKNO FROM E1;

--Question 2

WITH 
E1 AS (SELECT M1.SID FROM MAJOR M1 INNER JOIN MAJOR M2 ON M1.MAJOR = 'CS' AND M2.MAJOR = 'Math' AND M1.SID = M2.SID),
E2 AS (SELECT BOOK.BOOKNO, BOOK.TITLE, BUYS.SID FROM BUYS NATURAL JOIN BOOK NATURAL JOIN E1)
SELECT DISTINCT BOOKNO, TITLE FROM E2;

--Question 3

WITH
E1 AS (SELECT BOOKNO FROM BOOK WHERE PRICE < 50),
E2 AS (SELECT C1.CITEDBOOKNO FROM CITES C1 INNER JOIN CITES C2 ON C1.BOOKNO <> C2.BOOKNO AND C1.CITEDBOOKNO = C2.CITEDBOOKNO),
E3 AS (SELECT DISTINCT CITEDBOOKNO FROM E1 NATURAL JOIN E2),
E4 AS (SELECT SID, BOOKNO FROM BUYS INNER JOIN E3 ON BOOKNO = CITEDBOOKNO)
SELECT DISTINCT SID, BOOKNO FROM E4;

--QUESTION 4

WITH
E1 AS (SELECT BOOKNO FROM BOOK B1 NATURAL JOIN BOOK B2 WHERE B1.PRICE < B2.PRICE),
E2 AS (SELECT BOOKNO FROM BOOK B1 NATURAL JOIN BOOK B2 NATURAL JOIN BOOK B3 WHERE B1.PRICE < B2.PRICE AND B2.PRICE < B3.PRICE),
E3 AS ((SELECT BOOKNO FROM E1) EXCEPT (SELECT BOOKNO FROM E2))
SELECT BOOKNO FROM E3;

--QUESTION 5

WITH
E1 AS (SELECT SID FROM STUDENT),
E2 AS (SELECT BOOKNO FROM BOOK WHERE PRICE > 50),
E3 AS (SELECT BOOKNO, SID FROM BUYS, E1 WHERE BUYS.SID = E1.SID),
E4 AS (SELECT BOOKNO, SID FROM E2 NATURAL JOIN E3)
SELECT DISTINCT SID FROM E4;
